### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by limelect** [PascalGameDevelopment/PGDCommunityEngine#10]
Demo error
D10.2.3 window 7
I added asset dir

![Screenshot - 10_01_2024 , 12_07_19](https://github.com/PascalGameDevelopment/PGDCommunityEngine/assets/4199131/27d9d560-23fd-4534-8af8-236b1ef78f73)

**Comment by Dennis1000** [comment]
Thanks for your report. As this project seems to be abandoned, you may switch over to the [Castle Game Engine](https://github.com/castle-engine/castle-engine/), which is been actively developed.

**Comment by limelect** [comment]
I fixed it your resources path was wrong
